// examples/libraries/ViteNET.Solid/Assets/main.tsx
/**
 * Name: main.ts
 * Description: This is the main entry point for the app.
 */

import 'vite/modulepreload-polyfill';
/* @refresh reload */
import { render } from 'solid-js/web'

import './index.css'
import App from './App'

const root = document.getElementById('app')

render(() => <App />, root!)

// examples/libraries/ViteNET.React/Assets/main.tsx
/**
 * Name: main.ts
 * Description: This is the main entry point for the app.
 */

import 'vite/modulepreload-polyfill';
import { createRoot } from "react-dom/client";
import './index.css';
import App from "./App";

const appElement = document.querySelector<HTMLDivElement>('#app')!;


const root = createRoot(appElement);
root.render(<App />);
